name: CI

on:
  pull_request:
    branches: [master]

    jobs:
      buld:
        runs-on: Ubuntu-latest

        steps:
         - uses: actions/checkout@v3
         - name: Setup JDK 15
         - uses: actions/setup-java@v2
           with:
             java-version: '15'
             distribution: 'adopt'
        test:
          runs-on: Ubuntu-latest

          steps:
            - uses: actions/checkout@v3
            - name: Setup JDK 15
            - uses: actions/setup-java@v2
              with:
                java-version: '15'
                distribution: 'adopt'

          run: mvn -B clean test